### ISSUE TITLE
USB 1.0 Descriptors Do Not Work

### ISSUE THREAD

**Issue by insolace** [midi2-dev/usbMIDI2DescriptorBuilder#5]
This is a follow-up to my previous issue, although it is different in nature.

The USB descriptors generated by the JSON below do not work. The intention is to create an asymmetric port configuration with three host outputs and one host input, and while the port names show up correctly in MacOS, no data flows. The descriptors generated have embedded IN jacks connected to the BULK IN endpoint, and embedded OUT jacks connected to the BULK OUT endpoint, which I believe is not correct. 

I've found the USB MIDI spec can be confusing with it's mixing of IN and OUT references, embedded external, etc. After some experimentation and re-reading of the spec, here is my understanding of the correct USB signal flow, which I've confirmed is what we are using with our 8051 USB devices:

```
Host MIDI OUT Port
        |
        V
BULK OUT ENDPOINT (must list all embedded jacks it connects to, the jack order here determines how MacOS lists the ports)
        |
        V
Embedded MIDI IN Jack (MacOS uses the iJack string here to label the port)
        |
        V
External MIDI OUT Jack (with source jack id matching embedded MIDI IN, MacOS doesn't use iJack string referenced here)
        |
        V
---------------------------------------------
[Device firmware / USB peripheral lives here]
---------------------------------------------
        |
        V
External MIDI IN Jack (MacOS doesn't use iJack string referenced here)
        |
        V
Embedded MIDI OUT Jack (with source jack id matching external MIDI IN, MacOS uses the iJack string here to label the port)
        |
        V
BULK IN ENDPOINT (must list all embedded jacks it connects to)
        |
        V
Host MIDI IN Port 
```

Questions for @AmeNote-MikeKent:

- Does the above look correct to you?
- Are the external jacks necessary if they aren't actually associated with physical ports on the device? In other words, do we need to define an external jack for the keys on a keyboard controller, or will an embedded jack alone suffice? MacOS doesn't seem to care if I omit the External Output jacks from the HOST OUT -> DEVICE IN ports or the External Input jacks from the DEVICE OUT -> HOST IN ports, however this breaks things on Windows and the device won't enumerate. 
- It seems that the endpoint descriptors have to come after the jacks are defined, moving them before the jacks breaks them on MacOS. Can you confirm this is correct per the spec?
- Assuming my understanding above is correct, I'm having trouble getting a (host ports perspective) 3 out, 1 in device to enumerate properly. It's working on windows, but on MacOS all messages sent to ports 1 and 2 are using cable code 0, and messages sent to port 3 use cable code 1. I'll send you an email with details as this might be outside the scope of this issue.

JSON to generate the descriptors:
```
{
    "idVendor": "0xCAFE",
    "idProduct": "0x1d6b",
    "manufacturer": "ACME Enterprises",
    "manufacturerId": "0x7E0000",
    "version": "0x00010000",
    "product": "ACME Synth",
    "serialNumber": "abcd1234",
    "power": 250,
    "CDC": false,
    "CDCName": "ACME CDC",
    "processUmpManually": true,
    "endpoints": [
        {
            "name": "ACME Synth",
            "productId": "abcd1234",
            "familyId": "0xDEAD",
            "modelId": "0xBEEF",
            "MIDI1Itf": [
                {
                    "in": true,
                    "out": true,
                    "name": "Control Surface"
                },
                {
                    "in": false,
                    "out": true,
                    "name": "TRS MIDI Out"
                },
                {
                    "in": false,
                    "out": true,
                    "name": "CV In"
                }
            ],
            "defaultGTBProtocol": 1
        }
    ]
}
```

**Comment by starfishmod** [comment]
Ok so I have been doing some thourough testing on Linux for comparison.
On Linux, descriptors in a variety of combinations work (1 out, 1 in, 1 in/out, 2 in/out, 2 in 1 out, 1 in 2 out, 1 in 3 out) as expected.
I did find a bug for "1 in only" or "1 out only" where bNumEndpoints needed to equal 1. This is now fixed.

I can confirm on Mac OSX14 that there are odd issues with multichannel MIDI 1.0 Devices.
I have an RetroKits RK006 (2in/10Out) On Linux setting to output 7 only sends to 7. On Mac it only sends to the first cable.
I *think* this maybe a Mac issue

**Comment by starfishmod** [comment]
Also Mac doesn't like the iJack names beyond the first Cable Id

**Comment by insolace** [comment]
I’ve confirmed that Sonoma has issues that previous versions don’t. Andrew, do you have an older macos to test?On Feb 12, 2024, at 9:06 PM, Andrew Mee ***@***.***> wrote:﻿
Also Mac doesn't like the iJack names beyond the first Cable Id

**Comment by starfishmod** [comment]
@insolace  unfortunately I only have the one Mac 😟

**Comment by insolace** [comment]
Sorry, I should clarify. My 1in 3out descriptors work on Windows and mac os 13 or older, but not Sonoma (the system I dev on).  On Feb 12, 2024, at 9:19 PM, Eric Bateman ***@***.***> wrote:﻿I’ve confirmed that Sonoma has issues that previous versions don’t. Andrew, do you have an older macos to test?On Feb 12, 2024, at 9:06 PM, Andrew Mee ***@***.***> wrote:﻿
Also Mac doesn't like the iJack names beyond the first Cable Id

**Comment by insolace** [comment]
I am upgrading another mac to sonoma to confirm it isn’t just my system, I’ll report back when I confirm.If confirmed, can we ask Torry and his team to load these descriptors onto a protozoa to help them reproduce the issue?On Feb 12, 2024, at 9:29 PM, Andrew Mee ***@***.***> wrote:﻿
@insolace  unfortunately I only have the one Mac 😟

**Comment by insolace** [comment]
I've confirmed the issue is present on a freshly upgraded Sonoma system. Monterey, Ventura, and Windows 11 work correctly. 

My apologies for conflating this bug with the Descriptor Builder. Andrew if you've confirmed things are working on your end then I think we can close out this issue, and talk offline about how to report this bug to Apple.

**Comment by starfishmod** [comment]
Yes I'll close this and mark as a Sonoma bug. Certainly a worthwhile investigation though :+1:

**Comment by AmeNote-MikeKent** [comment]
Eric,

I think you and Andrew have tracked down the main problem. But back to your original email…


USB Endpoints are always labeled In/Out from Host viewpoint. I think most OS class drivers just expose the Embedded MIDI In/Out Jacks as ports available to applications. Topology deeper in the device is not exposed. So the OS generally only exposes something like this:

Host MIDI OUT Port (Device Destination Port)
        |
        V
BULK OUT ENDPOINT
        |
        V
Embedded MIDI IN Jack (MacOS uses the iJack string here to label the port)
        |
        V
---------------------------------------------
[Device firmware / USB peripheral lives here]
---------------------------------------------
        |
        V
Embedded MIDI OUT Jack
        |
        V
BULK IN ENDPOINT
        |
        V
Host MIDI IN Port (Device Source Port)


Mike.
￼


Mike Kent, CSO, Amenote Inc.
マイク・ケント
***@***.*** +1(778)999-5368

**Comment by AmeNote-MikeKent** [comment]
Thanks Mike.

Cheers,

*Eric Bateman*
Chief Executive Officer
Keith McMillen Instruments
***@***.***
510.910.0498 cell
