### ISSUE TITLE
Possible issue with bcdUSB value

### ISSUE THREAD

**Issue by EddieLotter** [midi2-dev/usbMIDI2DescriptorBuilder#6]
Forgive me if I'm wrong, this isn't my area of expertise, but it appears the bcdUSBMSB value "0x02" is being put in the bcdUSBLSB field of the USB device descriptor.

**Comment by starfishmod** [comment]
My understanding is that it's LSB then the MSB for all USB byte ordering.
I will confer with some USB orientated folks who are better versed than myself to confirm.
If you happen to find documentation before I do please feel free to post it here :)

**Comment by EddieLotter** [comment]
Agreed, which is why I think
```
uint8_t const desc_device[] = {
	0x12,	// bLength
	0x01,	// bDescriptorType = TUSB_DESC_DEVICE
	0x02,	// bcdUSBLSB
	0x00,	// bcdUSBMSB
```
should be
```
uint8_t const desc_device[] = {
	0x12,	// bLength
	0x01,	// bDescriptorType = TUSB_DESC_DEVICE
	0x00,	// bcdUSBLSB
	0x02,	// bcdUSBMSB
```
Unfortunately, the official USB spec doesn't include examples as byte arrays, so I can't point to anything official.

**Comment by starfishmod** [comment]
You were correct - thank-you for point this out :)
